export const TOP_FICTION_GENRES = [
  "Fiction",
  "Fantasy",
  "High Fantasy",
  "Epic Fantasy",
  "Urban Fantasy",
  "Dark Fantasy",
  "Science Fiction",
  "Sci-Fi",
  "SF",
  "Mystery",
  "Detective",
  "Crime Fiction",
  "Suspense",
  "Thriller",
  "Psychological Thriller",
  "Romance",
  "Contemporary Romance",
  "Historical Romance",
  "Paranormal Romance",
  "Historical Fiction",
  "Literary Fiction",
  "Horror",
  "Gothic",
  "Supernatural",
  "Paranormal",
  "Young Adult",
  "YA",
  "Adventure",
  "Action Adventure",
  "Dystopian",
  "Post-Apocalyptic",
  "Speculative Fiction",
  "Magical Realism",
  "Comedy",
  "Humor",
  "Graphic Novel",
  "Comics",
  "Short Stories",
  "Novella",
  "Drama",
  "Fairy Tales",
  "Mythology",
  "Folklore",
  "Steampunk",
  "Cyberpunk",
  "Time Travel",
  "Alternate History"
];

export const TOP_NON_FICTION_GENRES = [
  "Non Fiction",
  "Non-Fiction",
  "Biography",
  "Memoir",
  "Autobiography",
  "Self-help",
  "Personal Development",
  "Motivation",
  "Inspiration",
  "History",
  "Science",
  "Popular Science",
  "Travel",
  "Guide",
  "True Crime",
  "Philosophy",
  "Psychology",
  "Health",
  "Health & Fitness",
  "Fitness",
  "Wellness",
  "Business",
  "Finance",
  "Economics",
  "Entrepreneurship",
  "Politics",
  "Sociology",
  "Education",
  "Religion",
  "Spirituality",
  "Parenting",
  "Cookbook",
  "Art",
  "Photography",
  "Essay",
  "Journalism",
  "Reference",
  "Law",
  "Technology",
  "Environment",
  "Nature"
];

export const TOP_AUDIOBOOKS_GENRES = [
  "Audiobook",
  "Audio Book",
  "Audio",
  "Audio Drama",
  "Narrated",
  "Read Aloud",
  "Spoken Word",
  "Podcast"
];
